name: chewie
description: A video player for Flutter with Cupertino and Material play controls
version: 0.12.0
homepage: https://github.com/brianegan/chewie

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  # Custom video player with custom loadControl for exoplayer
  video_player: #^1.0.0
    git:
      url: https://github.com/ayush221b/plugins.git
      path: packages/video_player/video_player
      ref: f93cfee154c0eea639276669f72283fe9db5b2a9
  cupertino_icons: ^1.0.0
  wakelock: ^0.2.1+1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
